<a href="https://colab.research.google.com/github/vaishnavikale404/DataScienceLab_64/blob/main/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Algebra : Without NumPy Library(Manually)

Create a 3x3 square matrix and compute its determinant.

In [ ]:

A = [[1, 2, 3],
[0, 1, 4],
[5, 6, 0]]
def determinant(m):
  a, b, c = m[0]
  d, e, f = m[1]
  g, h, i = m[2]

  det = (a * (e * i - f * h)) - (b * (d * i - f * g)) + (c * (d * h - e * g))
  return det
det_A = determinant(A)
print(f"Determinant of A: {det_A}")

Determinant of A: 1


 Find the inverse of the matrix

In [ ]:
#Inverse of a 3x3 Matrix ---
def inverse(m):
  det = determinant(m)
  if det == 0:
    return "Matrix is singular, no inverse."

  # Matrix of Cofactors
  # We find the determinant of the 2x2 minor for each element and apply sign
  def det2x2(a, b, c, d):
    return a * d - b * c

  # Calculating Adjugate Matrix (Transpose of Cofactors)
  # The inverse matrix M_inv = (1/det) * adj(M)
  # adj(M) is the transpose of the cofactor matrix C.
  # Here we compute the adjugate matrix elements divided by the determinant directly.
  inv = [
      [det2x2(m[1][1], m[1][2], m[2][1], m[2][2]) / det,   # Adjugate[0][0] / det
       -det2x2(m[0][1], m[0][2], m[2][1], m[2][2]) / det,  # Adjugate[0][1] / det
       det2x2(m[0][1], m[0][2], m[1][1], m[1][2]) / det],  # Adjugate[0][2] / det

      [-det2x2(m[1][0], m[1][2], m[2][0], m[2][2]) / det,  # Adjugate[1][0] / det
       det2x2(m[0][0], m[0][2], m[2][0], m[2][2]) / det,   # Adjugate[1][1] / det
       -det2x2(m[0][0], m[0][2], m[1][0], m[1][2]) / det], # Adjugate[1][2] / det

      [det2x2(m[1][0], m[1][1], m[2][0], m[2][1]) / det,   # Adjugate[2][0] / det
       -det2x2(m[0][0], m[0][1], m[2][0], m[2][1]) / det,  # Adjugate[2][1] / det
       det2x2(m[0][0], m[0][1], m[1][0], m[1][1]) / det]   # Adjugate[2][2] / det
  ]
  return inv

if det_A != 0:
  print("\nInverse of Matrix A:")
  for row in inverse(A):
    # Using string formatting to truncate to 2 decimals as requested earlier
    print([f"{x:.2f}" for x in row])
else:
  print("\nMatrix A is singular.")


Inverse of Matrix A:
['-24.00', '18.00', '5.00']
['20.00', '-15.00', '-4.00']
['-5.00', '4.00', '1.00']


Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20

In [ ]:
# --- Solving 2x2 System (Cramer's Rule) ---
# 2x + 3y = 10
# 4x + 5y = 20
def solve_2x2(coeffs, consts):
  a, b = coeffs[0]
  c, d = coeffs[1]
  e, f = consts
  D = (a * d) - (b * c)
  if D == 0:
    return "No unique solution"
  Dx = (e * d) - (b * f)
  Dy = (a * f) - (e * c)
  return [Dx / D, Dy / D]
B = [[2, 3], [4, 5]]
C = [10, 20]
sol = solve_2x2(B, C)
print(f"\nSolution (x, y): {sol}")


Solution (x, y): [5.0, -0.0]


Linear Algebra : Using NumPy Library

In [ ]:
import numpy as np

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
det = np.linalg.det(A)
deter = int(det * 100) / 100
print("Matrix A:")
print(A)
print(f"Determinant of the matrix: {deter:.2f}")

Matrix A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant of the matrix: 0.99


In [ ]:
# Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
print("Matrix A:")
print(A)

# Find inverse
if np.linalg.det(A) != 0:
  inverse = np.linalg.inv(A)
  print("Inverse of the matrix:")
  print(inverse)
else:
  print("Inverse does not exist (determinant is zero).")

Matrix A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
# Coefficient matrix
A = np.array([[2, 3],
              [4, 5]])
# Constant matrix
B = np.array([10, 20])

# Solve the equations
solution = np.linalg.solve(A, B)

print("Solution of the given system:")
print("x =", solution[0])
print("y =", solution[1])

Solution of the given system:
x = 5.0
y = 0.0
